# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgramasDeMantenimientoRealizados.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProgramasDeMantenimientoRealizados(object):
    def setupUi(self, ProgramasDeMantenimientoRealizados):
        ProgramasDeMantenimientoRealizados.setObjectName("ProgramasDeMantenimientoRealizados")
        ProgramasDeMantenimientoRealizados.resize(780, 367)
        ProgramasDeMantenimientoRealizados.setStyleSheet("background-color: rgb(255, 249, 171);\n"
"")
        self.centralwidget = QtWidgets.QWidget(ProgramasDeMantenimientoRealizados)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 30, 711, 261))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(3)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(229)
        self.gridLayout.addWidget(self.tableWidget_4, 1, 0, 1, 1)
        ProgramasDeMantenimientoRealizados.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProgramasDeMantenimientoRealizados)
        QtCore.QMetaObject.connectSlotsByName(ProgramasDeMantenimientoRealizados)

    def retranslateUi(self, ProgramasDeMantenimientoRealizados):
        _translate = QtCore.QCoreApplication.translate
        ProgramasDeMantenimientoRealizados.setWindowTitle(_translate("ProgramasDeMantenimientoRealizados", "MainWindow"))
        self.label_4.setWhatsThis(_translate("ProgramasDeMantenimientoRealizados", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("ProgramasDeMantenimientoRealizados", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">PROGRAMAS DE MANTENIMIENTO</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">REALIZADOS</span></p></body></html>"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("ProgramasDeMantenimientoRealizados", "Folio"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("ProgramasDeMantenimientoRealizados", "Semestre"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("ProgramasDeMantenimientoRealizados", "Año"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProgramasDeMantenimientoRealizados = QtWidgets.QMainWindow()
    ui = Ui_ProgramasDeMantenimientoRealizados()
    ui.setupUi(ProgramasDeMantenimientoRealizados)
    ProgramasDeMantenimientoRealizados.show()
    sys.exit(app.exec_())
