# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OrdenesDeTrabajoAsignadas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OrdenesDeTrabajoAsignadas(object):
    def setupUi(self, OrdenesDeTrabajoAsignadas):
        OrdenesDeTrabajoAsignadas.setObjectName("OrdenesDeTrabajoAsignadas")
        OrdenesDeTrabajoAsignadas.resize(771, 349)
        OrdenesDeTrabajoAsignadas.setStyleSheet("background-color: rgb(255, 249, 171);")
        self.centralwidget = QtWidgets.QWidget(OrdenesDeTrabajoAsignadas)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 20, 611, 290))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.tableWidget_6 = QtWidgets.QTableWidget(self.widget)
        self.tableWidget_6.setObjectName("tableWidget_6")
        self.tableWidget_6.setColumnCount(4)
        self.tableWidget_6.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_6.setHorizontalHeaderItem(3, item)
        self.tableWidget_6.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.tableWidget_6, 1, 0, 1, 1)
        OrdenesDeTrabajoAsignadas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OrdenesDeTrabajoAsignadas)
        self.statusbar.setObjectName("statusbar")
        OrdenesDeTrabajoAsignadas.setStatusBar(self.statusbar)

        self.retranslateUi(OrdenesDeTrabajoAsignadas)
        QtCore.QMetaObject.connectSlotsByName(OrdenesDeTrabajoAsignadas)

    def retranslateUi(self, OrdenesDeTrabajoAsignadas):
        _translate = QtCore.QCoreApplication.translate
        OrdenesDeTrabajoAsignadas.setWindowTitle(_translate("OrdenesDeTrabajoAsignadas", "MainWindow"))
        self.label_4.setWhatsThis(_translate("OrdenesDeTrabajoAsignadas", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("OrdenesDeTrabajoAsignadas", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">ÓRDENES DE TRABAJO</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">ASIGNADAS</span></p></body></html>"))
        item = self.tableWidget_6.horizontalHeaderItem(0)
        item.setText(_translate("OrdenesDeTrabajoAsignadas", "No. Control"))
        item = self.tableWidget_6.horizontalHeaderItem(1)
        item.setText(_translate("OrdenesDeTrabajoAsignadas", "Tipo de servicio"))
        item = self.tableWidget_6.horizontalHeaderItem(2)
        item.setText(_translate("OrdenesDeTrabajoAsignadas", "Asignado"))
        item = self.tableWidget_6.horizontalHeaderItem(3)
        item.setText(_translate("OrdenesDeTrabajoAsignadas", "Fecha de aprobación"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OrdenesDeTrabajoAsignadas = QtWidgets.QMainWindow()
    ui = Ui_OrdenesDeTrabajoAsignadas()
    ui.setupUi(OrdenesDeTrabajoAsignadas)
    OrdenesDeTrabajoAsignadas.show()
    sys.exit(app.exec_())
