# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SolicitarServicios.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SolicituDeServicios(object):
    def setupUi(self, Form_SolicituDeServicios):
        Form_SolicituDeServicios.setObjectName("Form_SolicituDeServicios")
        Form_SolicituDeServicios.resize(772, 373)
        Form_SolicituDeServicios.setStyleSheet("background-color: rgb(255, 249, 171);")
        self.centralwidget = QtWidgets.QWidget(Form_SolicituDeServicios)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 30, 612, 281))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 7)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 1, 1, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 1, 5, 1, 1)
        self.dateEdit_7 = QtWidgets.QDateEdit(self.widget)
        self.dateEdit_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit_7.setObjectName("dateEdit_7")
        self.gridLayout.addWidget(self.dateEdit_7, 1, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 0, 1, 3)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 2, 3, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 0, 1, 2)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 3, 2, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 3, 4, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 3, 5, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 4, 0, 1, 3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.gridLayout.addWidget(self.textEdit_2, 5, 0, 1, 7)
        Form_SolicituDeServicios.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Form_SolicituDeServicios)
        self.statusbar.setObjectName("statusbar")
        Form_SolicituDeServicios.setStatusBar(self.statusbar)

        self.retranslateUi(Form_SolicituDeServicios)
        QtCore.QMetaObject.connectSlotsByName(Form_SolicituDeServicios)

    def retranslateUi(self, Form_SolicituDeServicios):
        _translate = QtCore.QCoreApplication.translate
        Form_SolicituDeServicios.setWindowTitle(_translate("Form_SolicituDeServicios", "MainWindow"))
        self.label_4.setWhatsThis(_translate("Form_SolicituDeServicios", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("Form_SolicituDeServicios", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">REALIZAR SOLICITUD</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">DE SERVICIO</span></p></body></html>"))
        self.label_20.setText(_translate("Form_SolicituDeServicios", "Folio:"))
        self.label_24.setText(_translate("Form_SolicituDeServicios", "Fecha de elaboración:"))
        self.label_21.setText(_translate("Form_SolicituDeServicios", "Departamento al que se dirige la solicitud:"))
        self.label_22.setText(_translate("Form_SolicituDeServicios", "Área solicitante:"))
        self.label_23.setText(_translate("Form_SolicituDeServicios", "Nombre y firma del solicitante:"))
        self.label_25.setText(_translate("Form_SolicituDeServicios", "Descripción del servicio o falla a reparar:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SolicituDeServicios = QtWidgets.QMainWindow()
    ui = Ui_Form_SolicituDeServicios()
    ui.setupUi(Form_SolicituDeServicios)
    Form_SolicituDeServicios.show()
    sys.exit(app.exec_())
