# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SolicitudesRealizadas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SolicitudesRealizadas(object):
    def setupUi(self, SolicitudesRealizadas):
        SolicitudesRealizadas.setObjectName("SolicitudesRealizadas")
        SolicitudesRealizadas.resize(773, 377)
        SolicitudesRealizadas.setStyleSheet("background-color: rgb(255, 249, 171);")
        self.centralwidget = QtWidgets.QWidget(SolicitudesRealizadas)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 30, 621, 290))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.tableWidget_5 = QtWidgets.QTableWidget(self.layoutWidget)
        self.tableWidget_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget_5.setObjectName("tableWidget_5")
        self.tableWidget_5.setColumnCount(4)
        self.tableWidget_5.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, item)
        self.tableWidget_5.horizontalHeader().setDefaultSectionSize(150)
        self.gridLayout.addWidget(self.tableWidget_5, 1, 0, 1, 1)
        SolicitudesRealizadas.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SolicitudesRealizadas)
        self.statusbar.setObjectName("statusbar")
        SolicitudesRealizadas.setStatusBar(self.statusbar)

        self.retranslateUi(SolicitudesRealizadas)
        QtCore.QMetaObject.connectSlotsByName(SolicitudesRealizadas)

    def retranslateUi(self, SolicitudesRealizadas):
        _translate = QtCore.QCoreApplication.translate
        SolicitudesRealizadas.setWindowTitle(_translate("SolicitudesRealizadas", "MainWindow"))
        self.label_4.setWhatsThis(_translate("SolicitudesRealizadas", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label_4.setText(_translate("SolicitudesRealizadas", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">SOLICITUDES DE</span></p><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">SERVICIOS REALIZADOS</span></p></body></html>"))
        item = self.tableWidget_5.horizontalHeaderItem(0)
        item.setText(_translate("SolicitudesRealizadas", "Folio"))
        item = self.tableWidget_5.horizontalHeaderItem(1)
        item.setText(_translate("SolicitudesRealizadas", "Depto solicitante"))
        item = self.tableWidget_5.horizontalHeaderItem(2)
        item.setText(_translate("SolicitudesRealizadas", "Fecha de realización"))
        item = self.tableWidget_5.horizontalHeaderItem(3)
        item.setText(_translate("SolicitudesRealizadas", "Orden de trabajo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SolicitudesRealizadas = QtWidgets.QMainWindow()
    ui = Ui_SolicitudesRealizadas()
    ui.setupUi(SolicitudesRealizadas)
    SolicitudesRealizadas.show()
    sys.exit(app.exec_())
